### ISSUE TITLE
Several tests occasionally flake due to missing cwd

### ISSUE THREAD

**Issue by alexanderkjall** [dimo414/bkt#40]
```
---- bkt_tests::with_env stdout ----
thread 'bkt_tests::with_env' panicked at 'assertion failed: `(left == right)`
  left: `"shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n"`,
 right: `""`', src/lib.rs:1317:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.63.0/library/core/src/panicking.rs:181:5
   4: bkt::bkt_tests::with_env
             at ./src/lib.rs:1317:9
   5: bkt::bkt_tests::with_env::{{closure}}
             at ./src/lib.rs:1311:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.63.0/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I looked at this a bit, and couldn't make sense of it, it seems to only happen inside the build environment and not with a normal `cargo test` on an arm64 machine, it also doesn't happen on any other architectures.

Build log: https://ci.debian.net/data/autopkgtest/testing/arm64/r/rust-bkt/34500844/log.gz

**Comment by dimo414** [comment]
That is very odd, as you say it sounds like a misconfigured build environment - namely it appears to be running the tests from a working directory that has since been deleted. In theory this could be worked around by retrieving the directory's inode rather than using `getcwd` but if I'm reading that stack trace correctly the cwd-lookup is happening in deeper code than bkt itself.

If supporting since-deleted cwds is important we should first add a unit test covering that case (which presumably fails) and then fix the implementation. But if the only known use case is this misconfigured environment it's probably a low priority fix.

**Comment by dimo414** [comment]
Ok I've been able to reproduce this locally on an x86_64 laptop (WSL) running the tests in a loop:

```
$ n=1; while RUST_BACKTRACE=1 cargo test --lib; do echo Passed $n; (( n += 1 )); done
...
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running unittests src/lib.rs (/tmp/bkt.target/debug/deps/bkt-7f4aab67b42eb584)

running 20 tests
test cache_tests::cache ... ok
test cache_tests::cleanup ... ok
test cache_tests::stable_hash ... ok
test bkt_tests::cloneable ... ok
test cmd_tests::debug_label ... ok
test file_lock_tests::locks ... ok
test cache_tests::scopes_support_special_chars ... ok
test cmd_tests::collisions ... ok
test cache_tests::lookup_ttls ... ok
test file_lock_tests::already_locked ... ok
test cache_tests::scoped ... ok
test bkt_tests::cwd_and_working_dir_share_cache ... ok
test bkt_tests::with_working_dir ... ok
test bkt_tests::with_modtime ... ok
test bkt_tests::streaming_same_output ... ok
test bkt_tests::streaming_refresh ... ok
test bkt_tests::streaming_to_file ... ok
test bkt_tests::cached ... ok
test bkt_tests::with_env ... FAILED
test bkt_tests::discard_failures ... ok

failures:

---- bkt_tests::with_env stdout ----
thread 'bkt_tests::with_env' panicked at 'assertion failed: `(left == right)`
  left: `"shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory\n"`,
 right: `""`', src/lib.rs:1554:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:229:5
   4: bkt::bkt_tests::with_env
             at ./src/lib.rs:1554:9
   5: bkt::bkt_tests::with_env::{{closure}}
             at ./src/lib.rs:1542:19
   6: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    bkt_tests::with_env

test result: FAILED. 19 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass `--lib`
```

But I'm stumped why it's failing. The tests themselves are running from the repo directory and don't muck with the cwd at all. I've added different debugging to try to see what directory bash is complaining about, but I still haven't seen any indication of the cause of this failure. I have seen a few other tests fail as well so it's not specific to `with_env`, though it is one of the more reliable failures. 🤔

**Comment by dimo414** [comment]
Over ~1k runs I saw:

with_env: 14
streaming_refresh: 1
streaming_same_output: 2
streaming_to_file: 4

I'm betting this is due to `cwd_and_working_dir_share_cache()` which changes the process' cwd. I'll see if I can improve that test.
